name: .NET

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish win-x64
      run: dotnet publish -c Release -r win-x64 --self-contained -o build/win-x64 -p:Flavor=build
    - name: Publish linux-x64
      run: dotnet publish -c Release -r linux-x64 --self-contained -o build/linux-x64 -p:Flavor=build
    - name: Publish linux-arm
      run: dotnet publish -c Release -r linux-arm64 --self-contained -o build/linux-arm64 -p:Flavor=build
    - name: Zip win-x64
    - uses: vimtor/action-zip@v1
      with:
        files: build/win-x64/
        dest: win-x64.zip
    - name: Zip linux-x64
    - uses: vimtor/action-zip@v1
      with:
        files: build/linux-x64/
        dest: linux-x64.zip
    - name: Zip linux-arm64
    - uses: vimtor/action-zip@v1
      with:
        files: build/linux-arm64/
        dest: linux-arm64.zip                
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
            Changes in this Release
            - First Change
            - Second Change
        draft: true
        prerelease: false
        artifacts: "*.zip"
